### ISSUE TITLE
Missing code from submodules in releases

### ISSUE THREAD

**Issue by Messlow** [kevinkreiser/prime_server#114]
The archived source code for releases is missing the submodules (for example the src/logging folder is empty in the [0.7.0 release .tar.gz file](https://github.com/kevinkreiser/prime_server/archive/refs/tags/0.7.0.tar.gz)).

**Comment by kevinkreiser** [comment]
This a problem with github releases and not something we control unfortunately. I haven't made a tagged release recently so maybe it's changed but last time I checked this is how it worked. Maybe I can make my own tars and upload them but for the meantime sadly it's a limitation of guthub

**Comment by Messlow** [comment]
Indeed you're right, I was not aware of this limitation... Thanks for taking the time to answer this :)

**Comment by kevinkreiser** [comment]
No problem it's always annoyed me too haha
