### ISSUE TITLE
Building from sources works in buster docker image but does not in bullseye

### ISSUE THREAD

**Issue by azarz** [kevinkreiser/prime_server#116]
Linked to #83 I think

I'm building prime_server from source using a Dockerfile.

From the `node:16-buster` image, the compilation works
```dockerfile
FROM node:16-buster as build

WORKDIR /home/prime-server
RUN apt-get update && apt-get install -y git cmake autoconf automake pkg-config libtool make gcc g++ lcov libcurl4-openssl-dev libzmq3-dev libczmq-dev
RUN git clone --depth 1 --recursive https://github.com/kevinkreiser/prime_server.git && cd prime_server &&\
./autogen.sh && ./configure && make && make install
```

However, from `node:16-bullseye`, if fails with th following error:
> config.status: executing libtool commands
>  CXX      src/prime_serverd-prime_serverd.o
>  CXX      src/libprime_server_la-prime_server.lo
>  CXX      src/libprime_server_la-zmq_helpers.lo
>  CXX      src/libprime_server_la-netstring_protocol.lo
>  CXX      src/libprime_server_la-http_util.lo
>  CXX      src/libprime_server_la-http_protocol.lo
>  CXXLD    libprime_server.la
>  CXXLD    prime_serverd
> /usr/bin/ld: src/prime_serverd-prime_serverd.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
> /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:913: prime_serverd] Error 1

```dockerfile
FROM node:16-bullseye as build

WORKDIR /home/prime-server
RUN apt-get update && apt-get install -y git cmake autoconf automake pkg-config libtool make gcc g++ lcov libcurl4-openssl-dev libzmq3-dev libczmq-dev
RUN git clone --depth 1 --recursive https://github.com/kevinkreiser/prime_server.git && cd prime_server &&\
./autogen.sh && ./configure && make && make install
```

**Comment by azarz** [comment]
I have managed to build `prime_server` on bullseye using the command `cmake -B build . && cmake --build build && make -C build install`

However, I the use it to build Valhalla. On the latest `master` version, it fails with the following error:
```

**Comment by kevinkreiser** [comment]
haha we just merged a pr that handles the install directories (#115 ) seems like, at least on bullseye, this doesnt work properly. my question to you would be, can you see what directory the headers are installed into? are there in `/usr/local/include` or `/usr/local/include/prime_server`? the code expects the latter but i could imagine that the former is happening since that pr potentially

**Comment by azarz** [comment]
The headers are indeed installed in `/usr/local/include`

```dockerfile
FROM node:16-bullseye as build

### Compilation de Valhalla
RUN apt-get update && \
apt-get install -y cmake make libtool pkg-config g++ gcc curl unzip jq lcov protobuf-compiler \
vim-common locales libcurl4-openssl-dev zlib1g-dev liblz4-dev libprotobuf-dev && \
apt-get install -y libgeos-dev libgeos++-dev libluajit-5.1-dev libspatialite-dev libsqlite3-dev wget sqlite3 spatialite-bin python3-shapely && \
apt-get install -y libsqlite3-mod-spatialite python3-pip

WORKDIR /home/prime-server
RUN apt-get install -y git cmake autoconf automake pkg-config libtool make gcc g++ lcov libcurl4-openssl-dev libzmq3-dev libczmq-dev
RUN git clone --depth 1 --recursive https://github.com/kevinkreiser/prime_server.git && cd prime_server && \
cmake -B build . && cmake --build build && make -C build install

RUN ls /usr/local/include

RUN ls /usr/local/include/prime_server
```

> Step 6/7 : RUN ls /usr/local/include
> http_protocol.hpp
> http_util.hpp
> netstring_protocol.hpp
> node
> prime_server.hpp
> zmq_helpers.hpp

> Step 7/7 : RUN ls /usr/local/include/prime_server
> ls: cannot access '/usr/local/include/prime_server': No such file or directory

**Comment by kevinkreiser** [comment]
Awesome thanks for confirming I'll fix it this evening!

**Comment by kevinkreiser** [comment]
@azarz should be fixed now, i tested with a clean install via docker to verify (at least on ubuntu, should work in debian as well)

**Comment by azarz** [comment]
I can confirm this works, thanks!
