### ISSUE TITLE
Error when updating Ubuntu packages

### ISSUE THREAD

**Issue by khamaileon** [kevinkreiser/prime_server#120]
While attempting to install Valhalla, I ran into this issue when trying to install prime-server via PPA:

```
> apt update

E: The repository 'https://ppa.launchpadcontent.net/kevinkreiser/prime-server/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

I am a root user in a Docker container running Ubuntu 22.04.

**Comment by nilsnolde** [comment]
Jep, there's no PPA release for 22.04 anymore. Best to build from source before building Valhalla or just use the installation script: https://github.com/valhalla/valhalla/blob/master/scripts/install-linux-deps.sh.

**Comment by khamaileon** [comment]
Yes I followed the steps in the README.

But I had this error so I thought I was missing prime-server:

```
valhalla_run_isochrone: error while loading shared libraries: libprime_server.so.0: cannot open shared object file: No such file or directory
```

I just re-tested, now it's working. 🤷

**Comment by khamaileon** [comment]
For future me and others who would come across this issue. The solution was to add the path of libprime_server.so.0 to LD_LIBRARY_PATH:
```shell
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
```
