### ISSUE TITLE
logging submodule is missing

### ISSUE THREAD

**Issue by bentley** [kevinkreiser/prime_server#20]
I’m trying to build valhalla on OpenBSD. prime_server appears to be a dependency of loki, but it can’t be built without the logging submodule. The repository listed in `.gitmodules` 404s.

Am I missing something obvious here?

**Comment by kevinkreiser** [comment]
can you show me the output of this:

    git clone https://github.com/kevinkreiser/prime_server.git ps
    cd ps
    git submodule init
    git submodule update

**Comment by bentley** [comment]
I was missing something obvious—the URLs 404 in a web browser, but not from git. `git submodule init` works properly. Sorry for the noise.
