### ISSUE TITLE
libzmq >= 4.1.4 difficult to install

### ISSUE THREAD

**Issue by TeXitoi** [kevinkreiser/prime_server#56]
Since some days, libzmq 4.1.4 is required. This version is only on debian experimental, which make it complicated to install.

**Comment by kevinkreiser** [comment]
@TeXitoi what distribution are you on? for trusty this was indeed a pain so i opted to backport it and stick the dependencies in a ppa: https://github.com/kevinkreiser/prime_server#grab-some-deps

**Comment by TeXitoi** [comment]
debian stable

**Comment by kevinkreiser** [comment]
ok i'll see what i can do. i dont know much about how the process differs for debian, but i am certain we can make debian packages somehow. in the mean time i will say its incredibly easy to install these from source, every single one of them is something like:

```
cd src_directory
./autogen.sh #only on some of them
./configure #zmq needs the libsodium flag passed
sudo make install
```

**Comment by TeXitoi** [comment]
OK, I'll add it to my build script : https://github.com/TeXitoi/valhalla-compile/

**Comment by kevinkreiser** [comment]
sweet, i can pr that if you like!

**Comment by TeXitoi** [comment]
I'm doing it. I must check that I can still have zmq from the distrib at the same time to not interfere with my navitia build.

**Comment by kevinkreiser** [comment]
ok no problem, let me know if you encounter issues

**Comment by TeXitoi** [comment]
OK, thanks

**Comment by TeXitoi** [comment]
https://github.com/zeromq/czmq is also needed?

**Comment by kevinkreiser** [comment]
yes, it has support for zbeacon which is a service discovery module. quite useful for automatic configuration (future feature of prime_server)

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/valhalla-compile/commit/34467277d71ab9dbf2b92444b6d0df5b70394e0b

Seems to work. Didn't use libsodium as it is not in trusty (for travis). No problem so far, and as I don't use https for the moment, I suspect I don't need libsodium.

**Comment by kevinkreiser** [comment]
that is correct. libsodium is not needed. the default packages in xenial had support for it enabled so i just kept it there as it was less work for me when back porting (was able to use the same source tarball). thanks for working through this on your end!
