### ISSUE TITLE
Remove autoconf based build system

### ISSUE THREAD

**Issue by TheMarex** [kevinkreiser/prime_server#69]
Currently this repository included two separate build systems that would have to be kept in sync with every modification. The readme still suggests using the autoconf version, which is broken for me with `glibc >= 2.2.5`.

To simplify the setup I would recommend removing the outdated autoconf build system and update the readme accordingly.

**Comment by kevinkreiser** [comment]
the project is small enough that keeping the autotools build system isnt a problem. currently the autotools build system is the only way to update the ppa and so for that reason i think the project should keep it for now.

in the future if we have time to figure out how to get cmake to play well with making proper debian packages for ppas then we can totally gut autotools
