### ISSUE TITLE
pirme_server license clarification

### ISSUE THREAD

**Issue by M4rtinK** [kevinkreiser/prime_server#70]
I'm trying to package Valhalla for Fedora and I've started by packaging prime_server, as Valhalla depends on it. While I've managed to build the [package](https://copr.fedorainfracloud.org/coprs/m4rtink/osm-scout-server/package/prime_server/) fine in COPR (a PPA-like service for Fedora), I have not been able to find an authoritative license for the project:

- the `LICENSE.md` file in the root of the project does not point to a license
- the [Ubuntu PPA](https://launchpad.net/~kevinkreiser/+archive/ubuntu/prime-server/+packages) has a `License: BSD-2-clause` specified in its metadata

So I would like to ask, what the intended license for prime_prime server ? Ideally it would be good if the license could be specified via a valid LICENSE file. 

Otherwise without a clear license I would most likely not be able to get the package through package review for the main Fedora repositories.

Thanks in advance for any information! :)

**Comment by kevinkreiser** [comment]
The `LICESNE.md` file is a symbolic link to the `COPYING` file which holds the license. The license is a 2 clause BSD license.
